const functions: Record<string, string> = {
    "+"				: "Add",
    "-"				: "Sub",
    "!-"			: "$Sub",
    "*"				: "Mul",
    "/"				: "Div",
    "!/"			: "$Div",
    "**"			: "Exp",
    "!**"			: "$Exp",
    "%"				: "Mod",
    "!%"			: "$Mod",
    "++"			: "Inc",
    "--"			: "Dec",
    "=="			: "Eql",
    "==="			: "EqlS",
    "!="			: "NEql",
    "!=="			: "NEqlS",
    ">"				: "Gtr",
    ">="			: "Geq",
    "<"				: "Lss",
    "<="			: "Leq",
    "&&"			: "And",
    "||"			: "Or",
    "!"				: "Not",
    "&"				: "BAnd",
    "|"				: "BOr",
    "^"				: "BXor",
    "~"				: "BNot",
    "<<"			: "BLS",
    ">>"			: "BRS",
    ">>>"			: "BRSZ",
    "typeof"		: "typeof",
    "instanceof"	: "instanceof",
    "void"			: "void",
    "in"			: "in"	
};

export default functions;
