const functions: Record<string, (...args: any[]) => any> = {
    "=+"			: (a: any) => +a,
    "+"				: (a: any, b: any) => a + b,
    "=-"			: (a: any) => -a,
    "-"				: (a: any, b: any) => a - b,
    "!-"			: (a: any, b: any) => b - a,
    "*"				: (a: any, b: any) => a * b,
    "/"				: (a: any, b: any) => a / b,
    "!/"			: (a: any, b: any) => b / a,
    "**"			: (a: any, b: any) => a ** b,
    "!**"			: (a: any, b: any) => b ** a,
    "%"				: (a: any, b: any) => a % b,
    "!%"			: (a: any, b: any) => b % a,
    "++"			: (a: any) => ++a,
    "--"			: (a: any) => --a,
    "=="			: (a: any, b: any) => a == b,
    "==="			: (a: any, b: any) => a === b,
    "!="			: (a: any, b: any) => a != b,
    "!=="			: (a: any, b: any) => a !== b,
    ">"				: (a: any, b: any) => a > b,
    ">="			: (a: any, b: any) => a >= b,
    "<"				: (a: any, b: any) => a < b,
    "<="			: (a: any, b: any) => a <= b,
    "&&"			: (a: any, b: any) => a && b,
    "||"			: (a: any, b: any) => a || b,
    "!"				: (a: any) => !a,
    "!!"			: (a: any) => !!a,
    "&"				: (a: any, b: any) => a & b,
    "|"				: (a: any, b: any) => a | b,
    "^"				: (a: any, b: any) => a ^ b,
    "~"				: (a: any) => ~a,
    "~~"			: (a: any) => ~~a,
    "<<"			: (a: any, b: any) => a << b,
    ">>"			: (a: any, b: any) => a >> b,
    ">>>"			: (a: any, b: any) => a >>> b,
    "typeof"		: (a: any) => typeof a,
    "instanceof"	: (a: any, b: any) => a instanceof b,
    "void"			: (a: any) => void a,
    "in"			: (a: any, b: any) => a in b
};

export default functions;
